### ISSUE TITLE
Import overlays from MotionBlue

### ISSUE THREAD

**Issue by cosmo0** [cosmo0/retropie-arcade-overlays#2]
See https://github.com/cosmo0/retropie-arcade-overlays/pull/1

@puxxi2003 
https://mega.nz/#!AR030QBY!cG6rynnPWhy6ZFF-sN4UcRO4QHNsXCvEPbIZm5eNCtc
https://drive.google.com/file/d/1Y2aqJoYfBskwH5A4eB3BRHvYC8epMdwA/view

**Comment by cosmo0** [comment]
I have checked the file, and indeed there are some overlays that I don't have. I hoped there would be more "realistic" overlays, but I guess "artworks" are fine too :D

I will have to re-work them to remove the "screen border" to make them match the existing ones.

Thanks @puxxi2003 ! :slightly_smiling_face:

**Comment by puxxi2003** [comment]
That's great to hear, i don't like the "screen border" too.

I dislike the shadows and scratches on the screen of the "realistic" overlays, to much realism for me.

**Comment by cosmo0** [comment]
I actually prefer small screen borders (like what you find in the MotionBlue image) than no border at all, but some of the overlays I grabbed have huge borders, and I really want everything to look the same.

And removing the borders everywhere is just much simpler for me to do (I have a few macros in Photoshop, one for each aspect ratio) than apply the same border everywhere...

**Comment by cosmo0** [comment]
@puxxi2003 MotionBlue is imported :)

The repository was getting too large for Git, and I couldn't push my changes anymore... so I split it in two:

https://github.com/cosmo0/retropie-overlays-arcade-artwork for the artwork style  
https://github.com/cosmo0/retropie-overlays-arcade-realistic for the realistic style

Later I will "soft-remove" the files in this repository and redirect users to the other two.

**Comment by puxxi2003** [comment]
You are the "Bezel-Master".

**Comment by cosmo0** [comment]
Hey @puxxi2003 
In case you're interested, I have created a tool to install the overlays (and manage roms) : https://github.com/cosmo0/retropie-arcade-manager/releases
